# Deploy TODO PWA to GitHub Pages
name: Deploy PWA

on:
  push:
    branches: [main]
  workflow_dispatch:
  # Optional: rebuild on a schedule to keep cached data fresh
  # schedule:
  #   - cron: '0 6 * * *'  # daily at 6am UTC

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
